# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v1.2.0
      with:
        # A directory to store and save the cache
        path: vendor/bundle
        # An explicit key for restoring and saving the cache
        key: my-app-cache-{{ checksum "Gemfile.lock" }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        # restore-keys: # optional  
    - name: Cache
      uses: actions/cache@v1.2.0
      with:
        # A directory to store and save the cache
        path: ~/.cache/yarn
        # An explicit key for restoring and saving the cache
        key: my-app-cache-{{ checksum "yarn.lock" }}
        
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6.3
    - name: Install bundle dependencies
      run: bundle install --path vendor/bundle
      
    - name: Install yarn dependencies
      run: yarn install --check-files --path ~/.cache/yarn
      
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        # Version of PostgreSQL to use
        postgresql version: latest # optional, default is latest
        # POSTGRES_DB - name for the default database that is created
        postgresql db: alpha_blog_test # optional, default is 
        # POSTGRES_USER - create the specified user with superuser power
        #postgresql user: # optional, default is 
        # POSTGRES_PASSWORD - superuser password
        #postgresql password: # optional, default is 
      
    - name: Setup Rails
      run: bin/setup
    - name: Run tests
      run: bundle exec rake
    
